# Generated by Django 6.0.6 on 2026-06-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, help_text='Загрузите видео в формате MP4 (опционально)', null=True, upload_to='projects/videos/', verbose_name='Видео проекта'),
        ),
    ]
