# Generated by Django 6.0.6 on 2026-06-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='projects/', verbose_name='Главное изображение'),
        ),
    ]
